### ISSUE TITLE
Visual Studio build of v1.6.1 fails when adding the LLE chips

### ISSUE THREAD

**Issue by stuerp** [Wohlstand/libOPNMIDI#126]
Tried to build the v1.6.1 release with Visual Studio and add the LLE code:

- MSBuild does not like two source files with the same filename. `"nuked_lle\ym3438.c"` conflicts with `"nuked\ym3438.c"`. The easy fix is to rename `"nuked_lle\ym3438.c"` to `"nuked_lle\ym3438_lle.c"`
- `"nuked_lle\ym3438.c"` tries to include `"test/fm.c"` which is not in the released source code.
- `"nuked_lle\ym3438.h"` tries to include `"test/fm.h"` and `"test/fmopn2.h"` which is not in the released source code.
-  UINT64 and INT64 are not defined when RSM_ENABLE = 0 causing an error in `"nuked_lle\ym3438.h"`
- `fmopna_impl_c.h` generates many errors because `dclk` is not defined in all FMOPA_ chip structures

And then I gave up. ;-)

**Comment by Wohlstand** [comment]
Hello! These files are junk, the 3438 is actually ran by different file. I quickly removed them from the build. Did you tried to just include everything of files tree? Try to build just via CMake, it should build just fine. If you still want to just include tree, pay attention on this list:
https://github.com/Wohlstand/libOPNMIDI/blob/master/CMakeLists.txt#L355-L388
These are files that actually included, others are just a junk that I forgot to remove.

**Comment by Wohlstand** [comment]
> Not CMake fan. I create MSBuild project files.

CMake actually can just generate the MSBuild project. The primary advantage of CMake is ability to generate build script for a large number of build systems including different versions of MSBuild, Xcode, NMake, GNU Make, BSD Make, Ninja, etc.


> I excluded them from the build but the fmopna_xxx.c files in fmopna_impl_c.h and that generates a lot of errors.

Can you show at least few of them?

Actually, if you didn't looked on my link above, I'll hint:
- To include YM2612 LLE, you need include these files:
```
src/chips/ym2612_lle.cpp
src/chips/ym2612_lle.h
src/chips/nuked_lle/nopn2.c
src/chips/nuked_lle/nopn2.h
src/chips/nuked_lle/fmopna_2612.c
src/chips/nuked_lle/fmopna_2612.h
```
- To include YM3438-LLE and YMF276-LLE (they both implemented by same group of files):
```
src/chips/ymf276_lle.cpp
src/chips/ymf276_lle.h
src/chips/nuked_lle/nopn2f.c
src/chips/nuked_lle/nopn2f.h
src/chips/nuked_lle/fmopn2.c
src/chips/nuked_lle/fmopn2.h
```
(Both emulators require `OPNMIDI_ENABLE_OPN2_LLE_EMULATOR` macro defined)
- And finally, to include OPNA-LLE (requires macro `OPNMIDI_ENABLE_OPNA_LLE_EMULATOR`):
```
src/chips/ym2608_lle.cpp
src/chips/ym2608_lle.h
src/chips/nuked_lle/nopna.c
src/chips/nuked_lle/nopna.h
src/chips/nuked_lle/fmopna_2608.c
src/chips/nuked_lle/fmopna_2608.h
```

And of course, suitable macros are required to be declared (by default they are off since these are optional emulators).

**Comment by stuerp** [comment]
> > Not CMake fan. I create MSBuild project files.
> 
> CMake actually can just generate the MSBuild project. The primary advantage of CMake is ability to generate build script for a large number of build systems including different versions of MSBuild, Xcode, NMake, GNU Make, BSD Make, Ninja, etc. I develop cross-platform software to run on a large number of platforms and operating systems, not just Windows only (my primary os is Linux Mint, and additionally I run Windows on VMs and I have different versions of macOS on three additional Mac Mini).

Oh, I'm not judging. I just didn't need to make the effort to start learning it.

> > I excluded them from the build but the fmopna_xxx.c files in fmopna_impl_c.h and that generates a lot of errors.
> 
> Can you show at least few of them?

```
fmopna_impl_c.h(168,15): error C2039: 'dclk': is not a member of 'fmopna_t'
```

> Actually, if you didn't looked on my link above, I'll hint:

*grin* I did read em.

Everything builds with the 1.6.0 MSBuild files until I define USE_NUKED_OPN2_LLE_EMULATOR and
USE_NUKED_OPNA_LLE_EMULATOR and starts adding the LLE source files.

**Comment by Wohlstand** [comment]
You don't need to include 2610, it's just unused here. I didn't yet implemented proper usage of it, so, just keep it unlisted.

**Comment by Wohlstand** [comment]
> That did it.

And? Does it works now?

**Comment by Wohlstand** [comment]
> [starman-YMF276LLE.zip](https://github.com/user-attachments/files/22463291/starman-YMF276LLE.zip)

P.S. Seems you still have the old version of the bank, please take a fresh xg.wopn from the repo (or the header from VLC plugin's directory).

**Comment by stuerp** [comment]
> > [starman-YMF276LLE.zip](https://github.com/user-attachments/files/22463291/starman-YMF276LLE.zip)
> 
> P.S. Seems you still have the old version of the bank, please take a fresh xg.wopn from the repo (or the header from VLC plugin's directory).

They're still the original files that I inherited from kode54. It never occurred to me to update them.

**Comment by Wohlstand** [comment]
Just for your sure:
- If it's a naked WOPN file, then just copy this https://github.com/Wohlstand/libOPNMIDI/blob/master/fm_banks/xg.wopn and place where it should be
- If it's a header-compiled file, then just copy this file https://github.com/Wohlstand/libOPNMIDI/blob/master/utils/winmm_drv/src/gm_opn_bank.h and place it instead original one at the foo_midi's sources.

**Comment by Wohlstand** [comment]
> Actually, there are 5 built-in banks in the component. I'll just whip up a small script to create fresh copies from the *.wopn files.

If you want headers, then the `wopn2hpp` utility in a set of libOPNMIDI (at `utils` directory) is made to quickly convert that.

**Comment by Wohlstand** [comment]
> > Nineko
> 
> Where do I find that one? It's not in the libopnmidi source archive.

In the freshest state of the repo: https://github.com/Wohlstand/libOPNMIDI/tree/master/fm_banks
